// <auto-generated />
using System;
using HospitalManagementSystem.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalManagementSystem.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260309210412_FixLabReportRelation")]
    partial class FixLabReportRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("HospitalManagementSystem.Web.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 3, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            PatientId = 1,
                            Status = "Onaylandı"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2026, 3, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            PatientId = 2,
                            Status = "Onaylandı"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2026, 3, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            PatientId = 3,
                            Status = "İptal"
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Web.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Dr. Mehmet Öz",
                            Phone = "05551112233",
                            RoomNumber = "K-02",
                            Specialization = "Kardiyoloji"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Op. Dr. Ayşe Yılmaz",
                            Phone = "05552223344",
                            RoomNumber = "G-05",
                            Specialization = "Genel Cerrahi"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Uzm. Dr. Kemal Sunal",
                            Phone = "05553334455",
                            RoomNumber = "D-10",
                            Specialization = "Dahiliye"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Op. Dr. Cüneyt Arkın",
                            Phone = "05554445566",
                            RoomNumber = "O-01",
                            Specialization = "Ortopedi"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Dr. Fatma Girik",
                            Phone = "05555556677",
                            RoomNumber = "C-08",
                            Specialization = "Çocuk Hastalıkları"
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Web.Models.LabReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("LabReports");
                });

            modelBuilder.Entity("HospitalManagementSystem.Web.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CitizenshipNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CitizenshipNumber = "12345678901",
                            CreatedAt = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1980, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ahmet Yılmaz",
                            Gender = "Erkek",
                            Phone = "05321112233"
                        },
                        new
                        {
                            Id = 2,
                            CitizenshipNumber = "23456789012",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Fatma Şahin",
                            Gender = "Kadın",
                            Phone = "05322223344"
                        },
                        new
                        {
                            Id = 3,
                            CitizenshipNumber = "34567890123",
                            CreatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1975, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ali Koç",
                            Gender = "Erkek",
                            Phone = "05323334455"
                        },
                        new
                        {
                            Id = 4,
                            CitizenshipNumber = "45678901234",
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1988, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ayşe Demir",
                            Gender = "Kadın",
                            Phone = "05324445566"
                        },
                        new
                        {
                            Id = 5,
                            CitizenshipNumber = "56789012345",
                            CreatedAt = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1960, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mustafa Çelik",
                            Gender = "Erkek",
                            Phone = "05325556677"
                        },
                        new
                        {
                            Id = 6,
                            CitizenshipNumber = "67890123456",
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2000, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Zeynep Kaya",
                            Gender = "Kadın",
                            Phone = "05326667788"
                        },
                        new
                        {
                            Id = 7,
                            CitizenshipNumber = "78901234567",
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mehmet Can",
                            Gender = "Erkek",
                            Phone = "05327778899"
                        },
                        new
                        {
                            Id = 8,
                            CitizenshipNumber = "89012345678",
                            CreatedAt = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Elif Yıldırım",
                            Gender = "Kadın",
                            Phone = "05328889900"
                        },
                        new
                        {
                            Id = 9,
                            CitizenshipNumber = "90123456789",
                            CreatedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1970, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Hasan Aydın",
                            Gender = "Erkek",
                            Phone = "05329990011"
                        },
                        new
                        {
                            Id = 10,
                            CitizenshipNumber = "01234567890",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sibel Ak",
                            Gender = "Kadın",
                            Phone = "05320001122"
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Web.Models.Appointment", b =>
                {
                    b.HasOne("HospitalManagementSystem.Web.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Web.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystem.Web.Models.LabReport", b =>
                {
                    b.HasOne("HospitalManagementSystem.Web.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystem.Web.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HospitalManagementSystem.Web.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
